/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.wholeAlert = true;

// self.addEventListener('message', (event) => {
//   if (event.data && event.data.type === 'SKIP_WAITING') {
//     self.skipWaiting();
//   }
// });






self.addEventListener('message', (event) => {
    if (!event.data) return;

    switch (event.data.type) {
        case 'SKIP_WAITING':
            self.skipWaiting();
            break;

        case 'SET_SELECTED_STOCKS':
            self.selectedStockNames = event.data.selectedStockNames;

            break;

        case 'SET_NEW_ENTRY_ALERT':
            self.newEntryAlert = event.data.newEntryAlert;
            console.log("선택");
            break;

        case 'SET_WHOLE_ALERT':
            self.wholeAlert = event.data.wholeAlert;
            break;

        default:
            console.warn('Unknown message type:', event.data.type);
            break;
    }
});

self.addEventListener('push', (event) => {
    if (!self.wholeAlert) {
        return;
    }


    if (event.data) {
        try {
            const data = event.data.json();
            const title = data.title || 'New Notification';
            const body = data.body || 'No content available.';
            const icon = data.icon || '/default-icon.png';
            const type = data.type || 'default'; // 알림 타입 (예: "신규")
            const stockName = data.stockName || ''; // 알림에 포함된 종목명


            // 알림 표시 조건 설정
            // const shouldShowNotification =
            //     type === '신규'
            //         ? (self.newEntryAlert === true) &&
            //         (!self.selectedStockNames || self.selectedStockNames.length === 0 || self.selectedStockNames.includes(stockName))
            //         : (!self.selectedStockNames || self.selectedStockNames.length === 0 || self.selectedStockNames.includes(stockName));
                // // "신규" 알림인 경우, newEntryAlert가 true여야 표시
                // (type === '신규' && self.newEntryAlert) ||
                // // "신규"가 아닌 경우 또는 선택된 종목에 포함된 경우 표시
                // (!self.selectedStockNames || self.selectedStockNames.length === 0 || self.selectedStockNames.includes(stockName));

            const shouldShowNotification =
                (type === '신규' ? self.newEntryAlert : true) &&
                (!self.selectedStockNames || self.selectedStockNames.length === 0 || self.selectedStockNames.includes(stockName));


            if (shouldShowNotification) {
                event.waitUntil(
                    self.registration.showNotification(title, {
                        body: body,
                        icon: icon,
                        data: { stockName, type }, // 알림 데이터 추가
                        tag: Date.now().toString(),
                        renotify: true
                    })
                );
            }
        } catch (error) {
            console.error('Error processing push message:', error);
        }
    } else {
        console.warn('Push event has no data.');
    }
});


// Any other custom service worker logic can go here.
